# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.trip_request_response_system_messages import TripRequestResponseSystemMessages  # noqa: E501
from swagger_client.rest import ApiException


class TestTripRequestResponseSystemMessages(unittest.TestCase):
    """TripRequestResponseSystemMessages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTripRequestResponseSystemMessages(self):
        """Test TripRequestResponseSystemMessages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.trip_request_response_system_messages.TripRequestResponseSystemMessages()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
