# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.stop_finder_location import StopFinderLocation  # noqa: E501
from swagger_client.rest import ApiException


class TestStopFinderLocation(unittest.TestCase):
    """StopFinderLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStopFinderLocation(self):
        """Test StopFinderLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.stop_finder_location.StopFinderLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
