# coding: utf-8

"""
    Trip Planner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class DepartureMonitorResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'error': 'ErrorResponse',
        'location': 'list[StopFinderLocation]',
        'stop_events': 'list[DepartureMonitorResponseStopEvent]'
    }

    attribute_map = {
        'version': 'version',
        'error': 'error',
        'location': 'location',
        'stop_events': 'stopEvents'
    }

    def __init__(self, version=None, error=None, location=None, stop_events=None, _configuration=None):  # noqa: E501
        """DepartureMonitorResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._version = None
        self._error = None
        self._location = None
        self._stop_events = None
        self.discriminator = None

        if version is not None:
            self.version = version
        if error is not None:
            self.error = error
        if location is not None:
            self.location = location
        if stop_events is not None:
            self.stop_events = stop_events

    @property
    def version(self):
        """Gets the version of this DepartureMonitorResponse.  # noqa: E501

        The version of the API that provided the response. Note that if this value is different to above, then the returned data may be different than expected. You can set the expected version using the `version` request parameter.    # noqa: E501

        :return: The version of this DepartureMonitorResponse.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this DepartureMonitorResponse.

        The version of the API that provided the response. Note that if this value is different to above, then the returned data may be different than expected. You can set the expected version using the `version` request parameter.    # noqa: E501

        :param version: The version of this DepartureMonitorResponse.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def error(self):
        """Gets the error of this DepartureMonitorResponse.  # noqa: E501

        If an error has occurred, this element contains information about the error.   # noqa: E501

        :return: The error of this DepartureMonitorResponse.  # noqa: E501
        :rtype: ErrorResponse
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this DepartureMonitorResponse.

        If an error has occurred, this element contains information about the error.   # noqa: E501

        :param error: The error of this DepartureMonitorResponse.  # noqa: E501
        :type: ErrorResponse
        """

        self._error = error

    @property
    def location(self):
        """Gets the location of this DepartureMonitorResponse.  # noqa: E501

        Contains a list of stops that were matched based on the supplied `type_dm` and `name_dm` request values. There must be exactly one location present for the `stopEvents` response data to be populated. Additionally, the `mode` request value must be set to `direct`.   # noqa: E501

        :return: The location of this DepartureMonitorResponse.  # noqa: E501
        :rtype: list[StopFinderLocation]
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this DepartureMonitorResponse.

        Contains a list of stops that were matched based on the supplied `type_dm` and `name_dm` request values. There must be exactly one location present for the `stopEvents` response data to be populated. Additionally, the `mode` request value must be set to `direct`.   # noqa: E501

        :param location: The location of this DepartureMonitorResponse.  # noqa: E501
        :type: list[StopFinderLocation]
        """

        self._location = location

    @property
    def stop_events(self):
        """Gets the stop_events of this DepartureMonitorResponse.  # noqa: E501

        Contains a list of departures/arrivals for the stop included in the `location` property of the response.   # noqa: E501

        :return: The stop_events of this DepartureMonitorResponse.  # noqa: E501
        :rtype: list[DepartureMonitorResponseStopEvent]
        """
        return self._stop_events

    @stop_events.setter
    def stop_events(self, stop_events):
        """Sets the stop_events of this DepartureMonitorResponse.

        Contains a list of departures/arrivals for the stop included in the `location` property of the response.   # noqa: E501

        :param stop_events: The stop_events of this DepartureMonitorResponse.  # noqa: E501
        :type: list[DepartureMonitorResponseStopEvent]
        """

        self._stop_events = stop_events

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DepartureMonitorResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DepartureMonitorResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DepartureMonitorResponse):
            return True

        return self.to_dict() != other.to_dict()
